name: Test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  zsh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo
        run: echo "Hello"
