name: Test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build-zsh-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: simonfong6/dotfiles-zsh
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: shells/zsh
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Print tags
        run: echo ${{ steps.meta.outputs.tags }}

  print-tags:
    runs-on: ubuntu-latest
    needs:
      - build-zsh-image
    steps:
      -
        name: Print tags
        run: echo {{ needs.build-zsh-image.outputs.tags }}

  zsh:
    runs-on: ubuntu-latest
    container:
      image: simonfong6/dotfiles-zsh:${{ needs.build-zsh-image.outputs.tags }}
    needs:
      - build-zsh-image

    steps:
      - uses: actions/checkout@v2

      - name: Clone Repository
        run: git clone https://github.com/simonfong6/dotfiles

      - name: Git Branch Name
        shell: zsh {0}
        working-directory: dotfiles
        run: |
          source shells/zsh/prompt.zsh
          echo $(git_branch_name)
