name: Test zsh

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

env:
  DOCKERHUB_USERNAME: simonfong6

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: simonfong6/dotfiles-zsh
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: shells/zsh
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  test-prompt:
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build-image.outputs.tags }}
    needs:
      - build-image

    steps:
      - uses: actions/checkout@v2

      - name: Clone Repository
        run: git clone https://github.com/simonfong6/dotfiles

      - name: Git Branch Name
        shell: zsh {0}
        working-directory: dotfiles
        run: |
          source shells/zsh/prompt.zsh
          echo "$(git_branch_name)"
          if [[ "$(git_branch_name)" != "- (master)" ]]; then
            exit 1;
          fi
